package com.nkapps.gitasaathi.auth

import android.app.Activity
import android.content.Context
import android.util.Log
import androidx.credentials.ClearCredentialStateRequest
import androidx.credentials.CredentialManager
import androidx.credentials.CustomCredential
import androidx.credentials.GetCredentialRequest
import androidx.credentials.exceptions.GetCredentialCancellationException
import com.google.android.libraries.identity.googleid.GetGoogleIdOption
import com.google.android.libraries.identity.googleid.GoogleIdTokenCredential
import com.google.firebase.FirebaseApp
import com.google.firebase.auth.FirebaseAuth
import com.google.firebase.auth.GoogleAuthProvider
import com.nkapps.gitasaathi.data.UserManager
import com.nkapps.gitasaathi.firebase.GitaAnalytics
import com.nkapps.gitasaathi.firebase.GitaCrashlytics
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch

/**
 * GitaAuthManager manages Google Sign-In (OAuth) using Android Credential Manager API
 * and Firebase Authentication.
 *
 * Ensures:
 * - 100% Guest-First: users are never blocked by a login screen.
 * - Optional 1-Tap Google Sign-In from the profile menu.
 * - Graceful fallback when Firebase or Web Client ID is not yet configured.
 */
object GitaAuthManager {
    private const val TAG = "GitaAuthManager"
    private val scope = CoroutineScope(Dispatchers.Main)

    /**
     * Attempts to resolve the default Web Client ID generated by google-services plugin,
     * or null if Google Sign-In is not yet enabled in Firebase Console.
     */
    fun getWebClientId(context: Context): String? {
        val resId = context.resources.getIdentifier("default_web_client_id", "string", context.packageName)
        return if (resId != 0) {
            try {
                context.getString(resId).takeIf { it.isNotBlank() }
            } catch (_: Exception) {
                null
            }
        } else {
            null
        }
    }

    /**
     * Launches the official Google Sign-In flow using Android Credential Manager.
     */
    fun signInWithGoogle(
        activity: Activity,
        onResult: (Boolean, String?) -> Unit
    ) {
        if (FirebaseApp.getApps(activity).isEmpty()) {
            onResult(false, "Firebase अभी कॉन्फ़िगर नहीं है। कृपया google-services.json जांचें।")
            return
        }

        val webClientId = getWebClientId(activity)
        if (webClientId == null) {
            Log.w(TAG, "default_web_client_id not found in resources. Google Sign-In needs to be enabled in Firebase Console.")
            onResult(
                false,
                "Google Sign-In चालू करने के लिए Firebase Console > Authentication > Sign-in method में 'Google' चालू करें।"
            )
            return
        }

        val credentialManager = CredentialManager.create(activity)

        val googleIdOption = GetGoogleIdOption.Builder()
            .setFilterByAuthorizedAccounts(false)
            .setServerClientId(webClientId)
            .setAutoSelectEnabled(false)
            .build()

        val request = GetCredentialRequest.Builder()
            .addCredentialOption(googleIdOption)
            .build()

        scope.launch {
            try {
                val result = credentialManager.getCredential(activity, request)
                val credential = result.credential

                if (credential is CustomCredential && credential.type == GoogleIdTokenCredential.TYPE_GOOGLE_ID_TOKEN_CREDENTIAL) {
                    val googleIdTokenCredential = GoogleIdTokenCredential.createFrom(credential.data)
                    val idToken = googleIdTokenCredential.idToken
                    firebaseAuthWithGoogle(idToken, activity, onResult)
                } else {
                    onResult(false, "अमान्य Google क्रेडेंशियल प्राप्त हुआ।")
                }
            } catch (_: GetCredentialCancellationException) {
                Log.i(TAG, "User dismissed Google Sign-In prompt.")
            } catch (e: Exception) {
                Log.e(TAG, "Google Sign-In failed: ${e.message}", e)
                onResult(false, "Google Sign-In विफल: ${e.localizedMessage}")
            }
        }
    }

    private fun firebaseAuthWithGoogle(
        idToken: String,
        activity: Activity,
        onResult: (Boolean, String?) -> Unit
    ) {
        val authCredential = GoogleAuthProvider.getCredential(idToken, null)
        FirebaseAuth.getInstance().signInWithCredential(authCredential)
            .addOnCompleteListener(activity) { task ->
                if (task.isSuccessful) {
                    val firebaseUser = task.result?.user
                    if (firebaseUser != null) {
                        val name = firebaseUser.displayName
                            ?: firebaseUser.email?.substringBefore("@")
                            ?: "Gita Reader"
                        val email = firebaseUser.email ?: ""
                        val photoUrl = firebaseUser.photoUrl?.toString()
                        val uid = firebaseUser.uid

                        UserManager.getInstance(activity).registerOrUpdateUser(
                            displayName = name,
                            email = email,
                            photoUrl = photoUrl,
                            customUserId = uid
                        ) { success, errorMsg ->
                            GitaCrashlytics.setUserId(uid)
                            GitaAnalytics.logEvent("google_sign_in_success")
                            onResult(success, errorMsg)
                        }
                    } else {
                        onResult(false, "उपयोगकर्ता जानकारी प्राप्त नहीं हो सकी।")
                    }
                } else {
                    Log.e(TAG, "Firebase auth error: ${task.exception?.message}")
                    onResult(false, task.exception?.localizedMessage ?: "Firebase प्रमाणीकरण विफल")
                }
            }
    }

    /**
     * Signs out the user from Firebase and clears local credential state.
     */
    fun signOut(context: Context, onComplete: () -> Unit = {}) {
        try {
            FirebaseAuth.getInstance().signOut()
            val credentialManager = CredentialManager.create(context)
            CoroutineScope(Dispatchers.IO).launch {
                try {
                    credentialManager.clearCredentialState(ClearCredentialStateRequest())
                } catch (_: Exception) {}
            }
            UserManager.getInstance(context).logout()
        } catch (e: Exception) {
            Log.w(TAG, "Error during sign out: ${e.message}")
        }
        onComplete()
    }
}
